-- AlterTable
ALTER TABLE "SpotifyService" ADD COLUMN     "lastSong" TEXT,
ADD COLUMN     "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "songs" DROP NOT NULL,
ALTER COLUMN "songs" SET DATA TYPE TEXT;
